.factorize_liblinphone_rocky8: &docker_image_needs_platform_devtoolset_libl
  image: !reference [ .rocky8_test_libl_image_version, image ]
  needs:
    - rocky8-ninja-gcc
  variables:
    PLATFORM: linux-rocky8


account-suite-liblinphone-test:
  extends: .test-liblinphone-mr
  <<: *docker_image_needs_platform_devtoolset_libl
  variables:
    TESTS_LIBLINPHONE_SUITE: "Account"

account-creator-flexiapi-suite-liblinphone-test:
  extends: .test-liblinphone-mr
  <<: *docker_image_needs_platform_devtoolset_libl
  variables:
    TESTS_LIBLINPHONE_SUITE: "Account creator FlexiAPI"

